```{r}
library(randomForestSRC)
library(survival)
library(ggplot2)
library(dplyr)
library(tidyverse)
# install.packages('ggsurvfit')
library(ggsurvfit)
# install.packages("survminer")
library(survminer)

knitr::opts_knit$set(root.dir = "~/dl-survival-miRNA") 
```


```{r}
setwd("~/dl-survival-miRNA")
mxf.rwd = read.csv("simulation/MSKpair_MXF_merge.csv") |>
  column_to_rownames(var="key_0")
pmfh.rwd=read.csv("simulation/MSKpair_PMFH_merge.csv") |>
  column_to_rownames(var="key_0")


rwd <- rbind(mxf.rwd, pmfh.rwd)
rwd = rwd |>
  mutate(death.status=ifelse(DEATH_STATUS=="Alive", 0, 1))

rwd.fit = survfit(Surv(time = ttDeath, event = death.status) ~ 1, data=rwd)
ggsurvfit(rwd.fit) +
  labs(
    title = 'Survival',
    x = 'Time',
    y = 'Survival Probability'
  ) +
  scale_x_continuous(breaks = seq(0, 210, by=20)) +
  add_confidence_interval() +
  add_risktable() +
  add_quantile(y_value = 0.5, color = "gray50", linewidth = 0.75) +
  theme_bw()

rna.rwd = rwd[,1:1033]
sd(as.matrix(rna.rwd))

hist(as.matrix(rna.rwd)[rna.rwd>500000])
```


```{r}
# ## Load simulated miRNA (subset)
# mxf <- read.csv(file.path("..","data","MSKpair_MXF_5000.csv"))[,1:1033]
# pmfh <- read.csv(file.path('..','data',"MSKpair_PMFH_5000.csv"))[,1:1033]
# g.names = read.csv("../data/MSKpair_miRNA_names.csv")$mirna.names[1:1033] ## gene names
# 
# ## Load simulated survival
# survival = read.csv(file.path('..','data',"simulate_survival_10000.csv")) |>
#   column_to_rownames(var='X')
# 
# rna <- rbind(mxf, pmfh)
# colnames(rna) = g.names
# rna <- cbind(rna, survival)
train_data = read.csv(file.path('..','data',"simulate_survival_train.csv")) 
test_data = read.csv(file.path('..','data',"simulate_survival_test.csv"))

summary(train_data$time)
```

```{r}
fit = survfit(Surv(time, status)~1, data=train_data, conf.type="log-log")

fig <- ggsurvfit(fit) +
  labs(
    title = 'Survival',
    x = 'Time',
    y = 'Survival Probability'
  ) +
  scale_x_continuous(breaks = seq(0, max(train_data$time), by=20)) +
  add_confidence_interval() +
  add_risktable() +
  theme_bw()
fig
```

```{r}
# rna <- rna[1:500,]
rsf <- rfsrc(Surv(time, status) ~ ., data=train_data)
print(rsf)
```

```{r}
plot.survival.rfsrc(rsf)
```



